### ISSUE TITLE
A single sub-part in a multipart is not parsed

### ISSUE THREAD

**Issue by zerodeux** [rjbs/Email-MIME#10] opened 2014-02-10 20:13 UTC
The test below will print (with 1.925) :

    + multipart/alternative; boundary="--42"

Although I'd expect it to print :

    + multipart/alternative; boundary="--42"
         + text/plain

I've quickly read the RFC and it seems that a mixed or multipart would accept "one or more bodyparts", and thus should be still correct with only a single sub-part. I encountered this bug while working on a e-mail generated by Email::MIME itself (starting with a well-known text-and-HTML email by removing one of the alternative sub-part). So Email::MIME can generate a multipart with a single sub-part (which makes my software work) but cannot parse it back (which makes my tests fail).

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Email::MIME;

undef $/;
my $m = Email::MIME->new(<DATA>);
print $m->debug_structure;

__DATA__
From: Bob <bob@test.com>
To: Alice <alice@test.com>
Subject: Does not parse as expected
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="--42"

--42
MIME-Version: 1.0
Content-Type: text/plain

Some basic text part, but no alternative.

--42
```

**Comment by labrown** [comment] 2015-07-29 01:16
I got this module for my July assignment in the CPAN Pull Request Challenge.

I think you have a bug in your example:

`boundary="--42"`

should be

`boundary="42"`


If you are generating Email::MIME messages with the leading double dash '--' in the boundary attribute than you are generating broken messages, as far as I can tell.

There is also a bug in debug_structure for which I will be submitting a pull request.

**Comment by rjbs** [comment] 2015-08-02 00:33
I think that any problem remaining after the above is a duplicate of #14.  Closing this in favor of that.

**Closed by rjbs** 2015-08-02 00:33 UTC
